#attention: uppercase key will automatically convert to lowercase, and I don't know why

mysql:
  dbname  : "blog"
  host    : "127.0.0.1"
  port    : "3306"
  user    : "root"
  pass    : "123"
  sslmode : "false"
session:
  session_hash_secret : "the-big-and-secret-hash-key-here"
  session_block_secret : "lot-secret-of-characters-big-too"
port: ":8001"